=== Universitatsbibliothek-Trier/TEI-Enrichment/tei_enrichment/src/main/resources/schemes/ListSchemes/places_scheme.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- @author       René Ackels
Copyright (c) 2024 Universität Trier

This file is part of TEI-Enrichment.

TEI-Enrichment is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

TEI-Enrichment is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.tei-c.org/ns/1.0"
  xmlns:self="http://www.tei-c.org/ns/1.0" elementFormDefault="qualified"
  attributeFormDefault="unqualified" xmlns:mods="http://www.loc.gov/mods/v3">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace"
    schemaLocation="https://www.w3.org/2009/01/xml.xsd" />


  <xs:element name="TEI">
    <xs:complexType>
      <xs:all>
        <xs:element name="teiHeader" type="self:TeiHeader" />
        <xs:element name="text" type="self:Text" />
      </xs:all>
      <xs:attribute name="version">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:pattern value="\d+.\d" />
          </xs:restriction>
        </xs:simpleType>
      </xs:attribute>
      <xs:anyAttribute />
    </xs:complexType>
  </xs:element>

  <xs:complexType name="TeiHeader">
    <xs:sequence>
      <xs:element name="fileDesc" type="self:FileDesc" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="version">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="\d+.\d" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="ID">
      <xs:simpleType>
        <xs:restriction base="xs:string">
          <xs:pattern value="merian\d{4}topographia" />
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="FileDesc">
    <xs:sequence>
      <xs:element name="titleStmt" type="self:TitleStmt" />
      <xs:element name="extent" type="self:Extent" />
      <xs:element name="publicationStmt" type="self:PublicationStmt" />
      <xs:element name="sourceDesc" type="self:SourceDesc" minOccurs="1" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="Title">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="Extent">
    <xs:sequence>
      <xs:element name="measure" type="self:Measure" maxOccurs="2" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Measure">
    <xs:simpleContent>
      <xs:extension base="self:MeasureValue">
        <xs:attribute name="unit">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="words" />
              <xs:enumeration value="vols" />
            </xs:restriction>
          </xs:simpleType>
        </xs:attribute>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <xs:simpleType name="MeasureValue">
    <xs:restriction base="xs:integer" />
  </xs:simpleType>

  <xs:complexType name="EditionStmt">
    <xs:sequence>
      <xs:element name="edition" type="self:Edition" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>


  <xs:simpleType name="Edition">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="PublicationStmt">
    <xs:sequence>
      <xs:element name="publisher" type="self:Publisher" maxOccurs="unbounded" />
      <xs:element name="idno" type="self:Idno" maxOccurs="1"  minOccurs="0"/>
      <xs:element name="distributor" type="self:Distributor" maxOccurs="1"  minOccurs="0"/>
      <xs:element name="pubPlace" type="self:pubPlace" maxOccurs="1" minOccurs="0"/>
      <xs:element name="date" type="self:Date" maxOccurs="1"  minOccurs="0"/>
      <xs:element name="availability" type="self:Availability" maxOccurs="1"  minOccurs="0" />
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="Availability">
    <xs:sequence>
      <xs:element name="licence" type="self:Licence" maxOccurs="1" />
      <xs:element name="p" type="self:PAvail" maxOccurs="1" />
    </xs:sequence>
    <xs:attribute name="status">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="Licence" mixed="true">
    <xs:attribute name="target">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="PAvail">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="Distributor">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="Idno">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="Date" mixed="true">
    <xs:attribute name="when">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>


  <xs:simpleType name="pubPlace">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="Publisher" mixed="true">
    <xs:sequence>
      <xs:element name="orgName" type="self:OrgNameHeader" maxOccurs="1" minOccurs="0" />
    </xs:sequence>
    <xs:attribute name="ref">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="OrgNameHeader">
    <xs:restriction base="xs:string" />
  </xs:simpleType>


  <xs:complexType name="TitleStmt">
    <xs:sequence>
      <xs:element name="title" type="self:TitleStmtValue" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>

  <xs:simpleType name="Author">
    <xs:restriction base="xs:string" />
  </xs:simpleType>


  <xs:simpleType name="TitleStmtValue">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:complexType name="SourceDesc">
    <xs:sequence>
      <xs:element name="p" type="self:PAvail" maxOccurs="1" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="Text">
    <xs:all>
      <xs:element name="body" type="self:Body" minOccurs="0" maxOccurs="1" />
    </xs:all>
  </xs:complexType>

  <xs:complexType name="Body">
    <xs:all>
      <xs:element name="div" type="self:Div" minOccurs="0" maxOccurs="1" />
    </xs:all>
  </xs:complexType>


  <!-- from here: differences for entity lists -->
  <xs:complexType name="Div">
    <xs:all>
      <xs:element name="listPlace" type="self:ListPlace" minOccurs="0" maxOccurs="1" />
    </xs:all>
    <xs:anyAttribute />
  </xs:complexType>



  <xs:complexType name="ListPlace">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="place" type="self:Place"  maxOccurs="unbounded" />
    </xs:choice>
    <xs:anyAttribute />
  </xs:complexType>

  <xs:complexType name="Place">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="placeName" type="self:PlaceName"  maxOccurs="unbounded" />
      <xs:element name="label" type="self:Label"  maxOccurs="unbounded" />
      <xs:element name="location" type="self:Location"  maxOccurs="unbounded" />
      <xs:element name="note" type="self:Note"  maxOccurs="unbounded" />       
      <xs:element name="link" type="self:Link"  maxOccurs="unbounded" />
      <xs:element name="idno" type="self:PlaceIdno"  maxOccurs="unbounded" />              
                    
    </xs:choice>
    <xs:attribute name="type">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:anyAttribute />
  </xs:complexType>

  <xs:complexType name="Location">
    <xs:choice maxOccurs="unbounded">
      <xs:element name="region" type="self:Region"  maxOccurs="unbounded" />
      <xs:element name="geo" type="self:Geo"  maxOccurs="unbounded" />
      <xs:element name="country" type="self:Geo"  maxOccurs="unbounded" />
    </xs:choice>
  </xs:complexType>

  <xs:simpleType name="Geo">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="Region">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  
  <xs:complexType name="PlaceIdno" mixed="true">
    <xs:attribute name="type">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
    <xs:attribute name="subtype">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="Link">
    <xs:attribute name="target">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>


  <xs:complexType name="Note" mixed = "true">
    <xs:sequence>
      <xs:element name="list" type="self:List" maxOccurs="2" minOccurs="0"/>
    </xs:sequence>  
    <xs:attribute name="type">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:complexType name="List">
    <xs:sequence>
      <xs:element name="item" type="self:Item" maxOccurs="unbounded" />
    </xs:sequence>  
    <xs:attribute name="type">
      <xs:simpleType>
        <xs:restriction base="xs:string"/>
      </xs:simpleType>
    </xs:attribute>
  </xs:complexType>

  <xs:simpleType name="Item">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="Label">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

  <xs:simpleType name="PlaceName">
    <xs:restriction base="xs:string" />
  </xs:simpleType>

</xs:schema>

=== Universitatsbibliothek-Trier/TEI-Enrichment/tei_enrichment/src/main/resources/backup/merian_entities_places.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<TEI version="5.0" xmlns="http://www.tei-c.org/ns/1.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.tei-c.org/ns/1.0 ../resources/schemes/ListSchemes/places_scheme.xsd">
    <!-- <TEI> -->
    <teiHeader>
        <fileDesc>
            <titleStmt>
                <title> Merian online: Index vorhandener Entitäten. </title>
                <author>Team Merian online</author>
            </titleStmt>
            <editionStmt>
                <edition>Beta draft.</edition>
            </editionStmt>
            <extent>
                <!-- description of the size of the resource; we could add the amount of entitities
                automatically when the file is updated -->
            </extent>
            <publicationStmt>
                <publisher>Universitätsbibliothek Trier</publisher>
                <pubPlace>Trier</pubPlace>
                <date>2023</date>
                <idno>1</idno>
                <availability>
                    <p>CC-0-Lizenz</p>
                </availability>
            </publicationStmt>
            <sourceDesc>
                <p>Born digital</p>
            </sourceDesc>
        </fileDesc>
    </teiHeader>
    <text>
        <body>
            <div xml:id="merian_places">
                <!-- information about the source from which
                    the resource was derived, for example the entries and IDs of entitities we want to index -->
                <listPlace xml:id="entities_place">
                    <place xml:id="place_Nassau" type="memberstate">
                        <placeName>Nassau</placeName>
                        <placeName>Staat Nassau </placeName>
                        <placeName>Herzogtum Nassau </placeName>
                        <label>Staat</label>
                        <location>
                            <region>Rheinland-Pfalz</region>
                            <region>Hessen</region>
                            <geo>50.3167 7.8</geo>
                        </location>
                        <note>Hier könnte eine Kurzbeschreibung stehen</note>
                        <link target="merian_hessen.xml#band_07"></link>
                        <idno type="URI" subtype="GND">https://d-nb.info/gnd/4041265-9</idno>
                    </place>
                    <place xml:id="place_Schloss_Regensburg" type="memorial">
                        <placeName>Schloss Regensburg-Weichs</placeName>
                        <placeName>Schloss Weichs (Regensburg)</placeName>
                        <location>
                            <region>Bayern</region>
                            <geo>12.095560 49.015000</geo>
                        </location>
                        <link target="merian_hessen.xml#band_07_art_Schloss_Regensburg" />
                        <link target="merian_hessen.xml#band_07_figure_001_01" />
                        <link target="merian_hessen.xml#band_07"></link>
                        <idno type="URI" subtype="GND">https://d-nb.info/gnd/7695021-9</idno>
                    </place>
                    <place xml:id="place_Regensburg" type="place">
                        <!-- AdministrativeUnit type="place"
                            TerritorialCorporateBodyOrAdministrativeUnit: type="place"
                        BuildingOrMemorial: type="memorial" 
                        WayBorderOrLine: type="line?"
                        religiousterritory: type="place?"
                        NaturalGeographicUnit: type="natural?"
                        NameOfSmallGeographicUnitLyingWithinAnotherGeographicUnit: type="smallPlace"

                        Country: type="country"
                        Memberstate: type="memberState"
                    
                    -->
                        <placeName>Regensburg </placeName>
                        <location>
                            <region>Bayern</region>
                            <geo>48.92194 11.6819</geo>
                        </location>
                        <link target="merian_hessen.xml#band_07"></link>
                        <idno type="URI" subtype="GND">https://d-nb.info/gnd/4048989-9</idno>
                    </place>
                    <place xml:id="place_Schloss_Grüningen" type="memorial">
                        <placeName>Schloss Grüningen </placeName>
                        <location>
                            <region>Kanton Zürich</region>
                        </location>
                        <link target="merian_hessen.xml#band_07"></link>
                        <idno type="URI" subtype="GND">https://d-nb.info/gnd/4583907-4</idno>
                    </place>
                    <place xml:id="place_Schloss_Hexenagger" type="memorial">
                        <placeName>Schloss Hexenagger</placeName>
                        <location>
                            <region>Bayern</region>
                            <geo>011.686170 48.920580</geo>
                        </location>
                        <link target="merian_hessen.xml#band_07"></link>
                        <idno type="URI" subtype="GND">https://d-nb.info/gnd/4260868-5</idno>
                    </place>
                    <place xml:id="place_Deutschland" type="country">
                        <placeName>Deutschland</placeName>
                        <location>
                            <geo>010.500000 051.500000</geo>
                        </location>
                        <link target="merian_hessen.xml#band_07"></link>
                        <idno type="URI" subtype="GND">https://d-nb.info/gnd/4260868-5</idno>
                    </place>
                </listPlace>
            </div>
        </body>
    </text>
</TEI>
